### PR TITLE
tryCatch to still update build files if there is an error

### LINKED ISSUE #47: update build files even when remake::make fails partway through
if scmake successfully builds some files with `make` but is interrupted or fails partway through, the build/status files don't get built, which means the overall status database is in an inconsistent state. this shouldn't happen.

### PR DESCRIPTION
**Pull request by wdwatkins**
fixes #47

### CODE REVIEW

**Comment by aappling-usgs** [comment]
Cool! How did you verify/test that this is working?

**Comment by wdwatkins** [comment]
I added this target to the remake.yml in the `tasks_demo` example:
```

**Comment by aappling-usgs** [comment]
Ahh, great. Are you able to check in a `testthat` test, too?

**Comment by aappling-usgs** [comment]
Awesome! First merged PR of the sprint :confetti_ball:

**Pull request merged**
